version: "3.9"

services:
  vitaldata-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/vitaldata-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
    device_cgroup_rules:
      - "c 254:* rmw"
    volumes:
      - type: bind
        source: /dev
        target: /dev

  vitaldata:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/vitaldata:${TAG}
    devices:
      - "/dev/gpiochip0"
      - "/dev/verdin-uart1:/dev/verdin-uart1"

